import type { Metadata } from 'next';
import { Vazirmatn } from 'next/font/google';
import ThemeProvider from '@/components/Theme/ThemeProvider';
import './globals.css';
import { Box } from '@mui/material';

const vazir = Vazirmatn({
  variable: '--font-vazir-sans',
  subsets: ['latin', 'arabic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <ThemeProvider>
        <Box
          bgcolor="background.paper"
          className={`${vazir.variable}`}
          component="body"
        >
          {children}
        </Box>
      </ThemeProvider>
    </html>
  );
}
